version: '2'

volumes:
  postgres_data:
      driver: local

services:
  gateway-local:
    container_name: binance-api-gateway-local
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - 6600:6600
    depends_on:
      - postgres
    volumes:
      - ./:/app:z
    env_file:
      - extra/local.env

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: binance-api-gateway
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: password

