version: '2'

volumes:
  postgres_data:
      driver: local

services:
  gateway:
    container_name: binance-api-gateway
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ${PWD}:/heroku:z
    env_file:
      - extra/local.env

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: binance-api-gateway
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: password

